Repository GoogleCloudPlatform/microservices-demo, pull requests merged in 2020-10, with the labels that each got.

#405 Remove Troubleshooting documentation for obsolete Skaffold bug
  README.md
Labels: area/documentation, cla: yes, priority/P2, what/improvement

#357 Updated broken loadgenerator to support locust 1.0.2
  src/loadgenerator/loadgen.sh
  src/loadgenerator/locustfile.py
  src/loadgenerator/requirements.in
  src/loadgenerator/requirements.txt
Labels: cla: yes, priority/P0, what/bug

#378 Fix multiply item price by quantity
  src/checkoutservice/main.go
  src/frontend/handlers.go
Labels: area/frontend, cla: yes, priority/P1, what/bug

#410 Move to go modules
  src/checkoutservice/Dockerfile
  src/checkoutservice/Gopkg.lock
  src/checkoutservice/Gopkg.toml
  src/checkoutservice/go.mod
  src/checkoutservice/go.sum
  src/frontend/Dockerfile
  src/frontend/Gopkg.lock
  src/frontend/Gopkg.toml
  src/frontend/go.mod
  src/frontend/go.sum
  src/productcatalogservice/Dockerfile
  src/productcatalogservice/Gopkg.lock
  src/productcatalogservice/Gopkg.toml
  src/productcatalogservice/go.mod
  src/productcatalogservice/go.sum
  src/shippingservice/Dockerfile
  src/shippingservice/Gopkg.lock
  src/shippingservice/Gopkg.toml
  src/shippingservice/go.mod
  src/shippingservice/go.sum
Labels: area/build, cla: yes, priority/P2, what/improvement

#413 Update loadgenerator Dockerfile to fix Pip incompatibility
  src/loadgenerator/Dockerfile
Labels: area/loadgenerator, cla: yes, priority/P0, what/bug

#412 Fix commands to set up GitHub actions runner
  .github/workflows/README.md
Labels: area/build, cla: yes, priority/P2, what/bug

#364 Use buildkit by default
  skaffold.yaml
Labels: area/build, cla: yes, priority/P2, what/improvement

#407 Add footer refs to UI for session & request id
  src/frontend/static/styles/styles.css
  src/frontend/templates/footer.html
Labels: area/frontend, cla: yes, priority/P2, what/improvement

#420 Removed duplicate bash invocation
  src/checkoutservice/genproto.sh
Labels: cla: yes
