Repository GoogleCloudPlatform/microservices-demo, pull requests merged in 2021-12, with the labels that each got.

#649 Release v0.3.2
  release/kubernetes-manifests.yaml
Labels: cla: yes

#660 Migrate to new GitHub Action Runners & GKE PR Cluster
  .github/workflows/ci-master.yaml
  .github/workflows/ci-pr.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/install-dependencies.sh
  .github/workflows/push-deploy.yaml
Labels: do not merge

#670 go 1.17.5
  src/checkoutservice/Dockerfile
  src/checkoutservice/go.mod
  src/checkoutservice/go.sum
  src/frontend/Dockerfile
  src/frontend/go.mod
  src/frontend/go.sum
  src/productcatalogservice/Dockerfile
  src/productcatalogservice/go.mod
  src/productcatalogservice/go.sum
  src/shippingservice/Dockerfile
  src/shippingservice/go.mod
  src/shippingservice/go.sum
Labels: lang/go
